version: 0.0
os: linux
files:
 - source: /
   destination: /tmp/react2-deploy
hooks:
 BeforeInstall:
 - location: Scripts/Before_install.sh
 timeout: 300
 runas: ubuntu
 AfterInstall:
 - location: Scripts/after_install.sh
 timeout: 300
 runas: ubuntu
 ApplicationStart:
 - location: Scripts/Application_start.sh
 timeout: 300
 runas: ubuntu